version: "3.1"
services:
  mongocontainer:
    image: mongo
    ports:
    - 27017:27017
    networks:
    - driftavbrottnetwork

  # APP  ***************************************************************************************
  mdh-driftavbrott-gui:
    build: docker
    ports:
    - 8080:8080
    networks:
    - driftavbrottnetwork

networks:
  driftavbrottnetwork:
