version: "3.1"
services:
  mongo:
    image: mongo
    ports:
    - 27017:27017

  # APP  ***************************************************************************************
  mdh-driftavbrott-gui:
    build: .
    ports:
    - 8080:8080
    links:
    - mongo
